# Generated by Django 5.0.3 on 2024-08-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_rename_template_emailtemplate_html_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='html_content',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='filename',
            field=models.CharField(default='default_template.html', max_length=100),
        ),
    ]
