# Generated by Django 4.2.11 on 2024-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_post_url_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='none'),
        ),
    ]
