# Generated by Django 4.2.11 on 2024-11-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0010_remove_profile_total_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
