# Generated by Django 4.2.11 on 2024-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0011_remove_profile_category_remove_profile_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='KasiAlgo.png', upload_to='kasi_pics'),
        ),
    ]
